name = "owned-greeter"
deployers = ["0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"]
version = "0.0.1"
preset = "router"

[pull.greeter]
source = "owned-greeter"

[router.Router]
contracts = ["greeter.Greeter"]
