# example file to be used for testing out gitops txs,
# DO NOT PUBLISH TO THE REGISTRY

name = "owned-greeter"
version = "0.0.2"
preset = "pull"

[setting.greeting]
defaultValue = "some-greet-update"

[pull.greeter]
source = "owned-greeter"

[invoke.setGreeting]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["<%= settings.greeting %>"]
