name = "owned-greeter"
version = "<%= package.version %>"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]

[setting.salt]
defaultValue = "owned-greeter"

[contract.Greeter]
artifact = "Greeter"
salt = "<%= settings.salt %>"

[contract.ExampleContract]
artifact = "ExampleContract"
salt = "<%= settings.salt %>"
