name = "owned-greeter-juan"
version = "0.0.1"
preset = "router"
deployers = ["0x88e224762460f5aAcA3Bde86dA4EFa9B13662b80", "0x7f28058F0b989430C7397782F797e300CDc10042"]

[clone.greeter]
source = "owned-greeter"
target = "owned-greeter-juan:0.0.1@greeter"

[router.Router]
contracts = ["greeter.Greeter"]

[invoke.setGreeting]
target = ["Router"]
from = "0x7f28058F0b989430C7397782F797e300CDc10042"
func = "setGreeting"
args = ["router hello"]
