name = "owned-greeter"
version = "<%= package.version %>"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]
deployers = ["0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"]

[setting.salt]
defaultValue = "owned-greeter"

[contract.Greeter]
artifact = "src/Greeter.sol:Greeter"
salt = "<%= settings.salt %>"
