name = "owned-greeter"
version = "<%= package.version %>"
description = "Simple greeter project that can be owned"
preset = "inject"

[setting.salt]
defaultValue = "owned-greeter"

[pull.ownedGreeter]
source = "owned-greeter:0.0.6"

[invoke.setGreeting]
target = ["ownedGreeter.Greeter"]
func = "setGreeting"
args = ["<%= console.log(window.fetch('https://usecannon.com')) || 'new greeting' %>"]
depends = ['pull.ownedGreeter']
