name = "owned-greeter"
version = "0.0.1"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]
preset = "testing-3"

[setting.salt]
defaultValue = "owned-greeter-testing-b"

[clone.greeter]
source = "owned-greeter"
target = "owned-greeter:0.0.0@with-testing-3"
options.salt = "<%= settings.salt %>"

[invoke.setGreeting]
target = ["greeter.Greeter"]
func = "setGreeting"
args = ["example greet 3"]
