name = "owned-greeter"
version = "<%= package.version %>"
description = "Simple greeter project that can be owned"
keywords = ["sample", "greeter", "owned"]
deployers = ["0xca7777aB932E8F0b930dE9F0d96f4E9a2a00DdD3"]
preset = "compat"

[var.settings]
salt = "owned-greeter"

[clone.greeter]
source = "owned-greeter:latest@main"
target = "owned-greeter:0.0.1@compat-clone"

[deploy.Greeter]
artifact = "Greeter"
salt = "<%= settings.salt %>"

[contract.GreeterLegacy]
artifact = "Greeter"
salt = "<%= settings.salt %>"
